### ISSUE TITLE
Quarto check status

### ISSUE THREAD

**Issue by PaulineBodson** [reinhrst/nitwit2gitwit#6]
Hi @reinhrst, 

Yesterday during the class, I was going through our GitHub and I bumped into this:
![Check status](https://github.com/user-attachments/assets/07e49ef6-2c56-4909-a409-3b7e17cc9087)
The Check status of quarto seems to have some troubles, do you know what it means? 

Pauline

**Comment by reinhrst** [comment]
Yes! I explained a couple of weeks ago that it's possible to run some code after each commit. Generally this has two use-cases:

- Run automated tests (to make sure you did not introduce a bug when changing your code)
- Build and deploy the code

The Check status indicates if these steps ran successfully. This could be useful if for instance you have 100 automated tests, and you can quickly see that in the branch you are doing some big changes 50 of the 100 tests run, it shows you that you still have quite some work to be done there.

This repo builds the quarto presentation website, and then deploys it online. I guess this failed when I was in the quarto branch (but now works in the main branch). I actually just deleted the quarto branch since (as you can see from the 15 behind, 0 ahead) everything there was already merged to the main branch.
